---
- hosts: edge
  gather_facts: no
  vars:
    cmds: ['show version']
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: ../junos_secret.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider: "{{ creds }}"

  - name: RUN COMMAND
    junos_command:
      provider: "{{ provider }}"
      commands: "{{ cmds }}"
    register: output

  - debug: var=output.stdout

  - name: VERIFY HOSTNAME
    assert:
      that:
        - "'edge' in output.stdout[0]['software-information']['host-name']"
